version: '3.7'

services:

  app:
    build:
      context: ./../../
      dockerfile: ./etc/docker/php.Dockerfile
    container_name: busuu-level-test.app
    restart: unless-stopped
    tty: true
    volumes:
      - ./../../:/var/www
    networks:
      - busuu-level-test

networks:
  busuu-level-test:
    driver: bridge
